# Generated by Django 4.1.7 on 2023-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='date2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
