# Generated by Django 6.1 on 2026-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="details",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
